name: StarRupture Dedicated Server (SteamCMD + Wine)
slug: starrupture_server
version: "1.0.6"

description: >
  StarRupture Dedicated Server as Home Assistant Add-on.
  Server configuration is done in-game.

url: https://github.com/cyclemat/HAOS---StarRupture-Dedicated-Server

arch:
  - amd64

startup: application
boot: auto
init: false
host_network: false

ports:
  7777/udp: null
  7777/tcp: null

ports_description:
  7777/udp: Game UDP (intern 7777)
  7777/tcp: Game TCP (intern 7777)

map:
  - share:rw

options:
  update_on_start: true

schema:
  update_on_start: bool
